version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_archen
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: archen_demo
      MYSQL_USER: archen
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - ./etc/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./etc/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
