import { getArchen } from '@/lib/graphql';
import { graphql } from '@/gql';

// A typed operation. `graphql()` (generated by graphql-codegen from
// etc/schema.graphql) returns a TypedDocumentNode, so the result and variables
// of archen.query() below are fully typed — no hand-written interfaces.
const RecentUsers = graphql(`
  query RecentUsers($limit: Int) {
    users(orderBy: ["-id"], limit: $limit) {
      id
      email
      meta
    }
  }
`);

export async function getRecentUsers(limit = 10) {
  const archen = await getArchen();
  const data = await archen.query(RecentUsers, { limit });
  return data.users; // typed as { id: number; email: string | null; meta: any }[]
}
